--- #Configuration for the AD/SCCM/ManagementServer

- hosts: adserver
  gather_facts: no
  tasks:
   - name: Install Git
     win_chocolatey:
       name: git
       state: latest

   - name: Install Visual Studio Code
     win_chocolatey:
       name: VisualStudioCode
       state: latest

   - name: Installing ProcMon test
     win_chocolatey:
       name: ProcMon
       state: latest

   - name: ensure print spooler service is stopped...no one should EVER PRINT AGAIN!!!!!
     win_service:
       name: spooler
       state: stopped

   - name: ensure SplashtopRemoteService is started
     win_service:
       name: SplashtopRemoteService
       state: started
       
   - name: Create directory called test in the root of c drive
     win_file:
       path: C:\Test
       state: directory
   
   - name: Add a file called test.txt (creates if not present, updates modification time if present)
     win_file:
       path: C:\Test\test.txt
       state: touch

   - name: Install Packer
     win_chocolatey:
       name: Packer
       state: latest
  
   - name: Install Terraform
     win_chocolatey:
       name: Terraform
       state: latest

