--- #Configuration for the AD/SCCM/ManagementServer

- hosts: adserver
  gather_facts: no
  tasks:
   - name: Install Git
     win_chocolatey:
       name: git
       state: latest

   - name: Install Visual Studio Code
     win_chocolatey:
       name: VisualStudioCode
       state: latest

   - name: Install ProcMon test
     win_chocolatey:
       name: ProcMon
       state: latest

   - name: ensure print spooler service is started
     win_service:
       name: spooler
       state: started

   - name: ensure SplashtopRemoteService is started
     win_service:
       name: SplashtopRemoteService
       state: started
       
   - name: Create directory called test in the root of c drive
     win_file:
       path: C:\Test
       state: directory
   
   - name: Add a file called test.txt (creates if not present, updates modification time if present)
     win_file:
       path: C:\Test\test.txt
       state: touch

   - name: Install Packer
     win_chocolatey:
       name: Packer
       state: latest
  
   - name: Install Terraform
     win_chocolatey:
       name: Terraform
       state: latest

   - name: Install Google Chrome
     win_chocolatey:
       name: GoogleChrome
       state: latest

   - name: Update homepage of browser to google.co.uk
     win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main
       name: 'Start Page'
       data: 'http://www.bing.com'
       type: string


